version: '2'
services:
  ranch2github:
    image: gmentsik/ranch2git
    environment:
      GIT_REPO_URL: https://github.com/username/repo.git
      GIT_REPO_USER: git-user
      GIT_REPO_PASS: git-password
      UPDATE_EVERY: 1h
    labels:
      io.rancher.container.create_agent: "true"
      io.rancher.container.agent.role: "environment"
    stdin_open: true
    network_mode: host
    tty: true